name: Build

on:
  push:
    branches: [ main, 2.x ]
  pull_request:
    branches: [ main, 2.x ]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony }}
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.4
          - 8.5
        symfony-version:
          - 6.4.*
          - 7.4.*
          - 8.0.*
        dependencies: [lowest, highest]
    name: 'PHP ${{ matrix.php-version }} + Symfony ${{ matrix.symfony-version }} + ${{ matrix.dependencies }} dependencies'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          tools: flex

      - name: "symfony/flex is required to install the correct symfony version"
        if: ${{ matrix.symfony-version }}
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require symfony/flex

      - name: "Configure Symfony version for symfony/flex"
        if: ${{ matrix.symfony-version }}
        run: composer config extra.symfony.require "${{ matrix.symfony-version }}.*"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: --prefer-dist

      - name: Run checks
        run: composer check
