name: Build

on:
  push:
    branches: [ main, 2.x ]
  pull_request:
    branches: [ main, 2.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony }}
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
        symfony:
          - 5.4.*
          - 6.4.*
          - 7.*
        dependencies: [lowest, highest]
        exclude:
          - php: '8.1' # Symfony 7 requires >=8.2
            symfony: 7.*
    name: 'PHP ${{ matrix.php }} + Symfony ${{ matrix.symfony }} + ${{ matrix.dependencies }} dependencies'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: flex

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-

      # Remove optional dependencies incompatible with Symfony 7
      - name: Remove symfony/messenger
        if: ${{ matrix.symfony == '7.*' }}
        run: composer remove --dev --no-update nesbot/carbon spatie/pdf-to-text

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --prefer-dist

      - name: Run checks
        run: composer check
